filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            equals:
              docker.container.labels.filebeat_enable: "true"
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"
              json.message_key: log  
              json.keys_under_root: true
              json.add_error_key: false
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~ 
  output.logstash:
    hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]
    bulk_max_size: 1024